// src/CommandRunner.Website.VueJs/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useAppStore } from './stores/app';
import { useTheme } from './composables/useTheme';
import { useKeyboardShortcuts } from './composables/useKeyboardShortcuts';
import { commandsApi } from './services/api';
import type { CommandDto, CommandExecutionResponse, FavoriteDirectoryDto, IterationExecutionResponse } from './services/api';

import HeaderButtons from './components/HeaderButtons.vue';
import AlertBanner from './components/AlertBanner.vue';
import ProfileSelector from './components/ProfileSelector.vue';
import DirectorySelector from './components/DirectorySelector.vue';
import CommandSelector from './components/CommandSelector.vue';
import CommandControls from './components/CommandControls.vue';
import CommandDetails from './components/CommandDetails.vue';
import CommandPreview from './components/CommandPreview.vue';
import OutputPanel from './components/OutputPanel.vue';
import ToastNotification from './components/ToastNotification.vue';
import SettingsDialog from './components/SettingsDialog.vue';
import AppIcon from './components/AppIcon.vue';

const store = useAppStore();
const { toggleTheme } = useTheme();

const selectedCommand = ref<CommandDto | null>(null);
const isExecuting = ref(false);
const output = ref('');
const settingsOpen = ref(false);
const focusMode = ref(false);
const showSuccessToast = ref(false);
const retryingApi = ref(false);

let abortController: AbortController | null = null;
let lastProgressSnapshot = '';

const availableDirectories = computed<FavoriteDirectoryDto[]>(() => {
  const directories = [...store.directories];
  const workingDirectory = selectedCommand.value?.workingDirectory;

  if (workingDirectory && !directories.some((d) => d.path === workingDirectory)) {
    const pathParts = workingDirectory.split('/').filter(Boolean);
    const name = pathParts.at(-1) ?? workingDirectory;
    directories.push({
      id: `cmd-dir-${selectedCommand.value!.id}`,
      path: workingDirectory,
      name,
      createdAt: new Date().toISOString(),
      usageCount: 0,
    });
  }

  return directories;
});

function toggleFocusMode() {
  focusMode.value = !focusMode.value;
}

function handleBrowseClick() {
  const directoryPath = prompt('Enter directory path:', store.selectedDirectory?.path || '~/');
  if (!directoryPath?.trim()) return;

  const path = directoryPath.trim();
  const pathParts = path.split('/').filter(Boolean);
  const name = pathParts.at(-1) ?? path;

  const existing = store.directories.find((d) => d.path === path);
  if (existing) {
    store.setSelectedDirectory(existing);
    return;
  }

  const newDirectory: FavoriteDirectoryDto = {
    id: `dir-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`,
    path,
    name,
    createdAt: new Date().toISOString(),
    usageCount: 1,
  };
  store.addDirectory(newDirectory);
  store.setSelectedDirectory(newDirectory);
}

function handleCopyOutput() {
  navigator.clipboard.writeText(output.value);
}

function handleSaveLog() {
  const blob = new Blob([output.value], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `command-output-${new Date().toISOString().slice(0, 19)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function isIterationResult(result: unknown): result is IterationExecutionResponse {
  return typeof (result as IterationExecutionResponse)?.totalItems === 'number';
}

function isCommandResult(result: unknown): result is CommandExecutionResponse {
  return typeof (result as CommandExecutionResponse)?.exitCode === 'number';
}

async function handleExecuteCommand() {
  const command = selectedCommand.value;
  if (!command || !store.selectedProfile) return;

  abortController?.abort();
  abortController = new AbortController();
  lastProgressSnapshot = '';

  if (command.requireConfirmation) {
    const workingDir = store.selectedDirectory?.path || command.workingDirectory || '~/';
    const confirmed = confirm(
      `This command requires confirmation:\n\n${command.name}\n${command.executable} ${command.arguments}\n\nWorking Directory: ${workingDir}\n\nDo you want to proceed?`,
    );
    if (!confirmed) return;
  }

  isExecuting.value = true;
  const workingDirectory = store.selectedDirectory?.path || command.workingDirectory || '~/';
  output.value = command.iterationEnabled
    ? `Executing iteratively: ${command.executable} ${command.arguments}\nWorking Directory: ${workingDirectory}\nScanning subdirectories...\n\n`
    : `Executing: ${command.executable} ${command.arguments}\nWorking Directory: ${workingDirectory}\n\n`;

  try {
    const request = {
      commandId: command.id,
      profileId: store.selectedProfile.id,
      workingDirectory,
      userConfirmed: command.requireConfirmation,
    };

    let result: CommandExecutionResponse | IterationExecutionResponse;

    if (command.iterationEnabled) {
      result = await commandsApi.executeIterativeCommandWithStreaming(
        {
          ...request,
          iterationOptions: {
            maxDepth: 1,
            includeRootDirectory: false,
            skipErrors: true,
            stopOnFirstFailure: false,
            excludePatterns: [],
            includePatterns: [],
            maxParallelism: 1,
          },
        },
        {
          onItemStart: (itemPath) => {
            const dirName = itemPath.split(/[\\/]/).filter(Boolean).pop() || itemPath;
            output.value += `\n▶ Processing ${dirName}\n`;
          },
          onStdout: (itemPath, line) => {
            const dirName = itemPath.split(/[\\/]/).filter(Boolean).pop() || itemPath;
            output.value += `[${dirName}] ${line}\n`;
          },
          onStderr: (itemPath, line) => {
            const dirName = itemPath.split(/[\\/]/).filter(Boolean).pop() || itemPath;
            output.value += `[${dirName}][stderr] ${line}\n`;
          },
          onProgress: (progress) => {
            const snapshot = `${progress.processedItems}/${progress.totalItems}:${progress.successfulItems}:${progress.failedItems}:${progress.skippedItems}`;
            if (lastProgressSnapshot === snapshot) return;
            lastProgressSnapshot = snapshot;
            output.value += `[progress] ${progress.processedItems}/${progress.totalItems} (ok: ${progress.successfulItems}, failed: ${progress.failedItems}, skipped: ${progress.skippedItems})\n`;
          },
          onError: (message) => {
            output.value += `[error] ${message}\n`;
          },
        },
        abortController.signal,
      );
    } else {
      result = await commandsApi.executeCommandWithStreaming(
        request,
        {
          onStdout: (line) => {
            output.value += `${line}\n`;
          },
          onStderr: (line) => {
            output.value += `[stderr] ${line}\n`;
          },
          onError: (message) => {
            output.value += `[error] ${message}\n`;
          },
        },
        abortController.signal,
      );
    }

    let summary = '';

    if (command.iterationEnabled && isIterationResult(result)) {
      summary = 'Iterative execution completed\n';
      summary += `Total Items: ${result.totalItems}\n`;
      summary += `Successful: ${result.successfulItems}\n`;
      summary += `Failed: ${result.failedItems}\n`;
      summary += `Skipped: ${result.skippedItems}\n`;
      summary += `Execution Time: ${result.startedAt} - ${result.completedAt || 'In Progress'}\n\n`;

      if (result.itemResults.length > 0) {
        summary += 'Results by directory:\n\n';
        for (const item of result.itemResults) {
          const status = item.wasSuccessful ? '✅' : '❌';
          const dirName = item.itemPath.split('/').pop() || item.itemPath;
          summary += `${status} ${dirName}/\n`;
          if (item.output?.trim()) summary += `   Output: ${item.output.trim()}\n`;
          if (item.errorOutput?.trim()) summary += `   Error: ${item.errorOutput.trim()}\n`;
          if (item.executionTime) summary += `   Execution time: ${item.executionTime}\n`;
          if (!item.wasSuccessful && item.errorMessage) {
            summary += `   Error: ${item.errorMessage}\n`;
          } else if (item.wasSuccessful && !item.output?.trim() && !item.errorOutput?.trim()) {
            summary += '   Status: Command completed successfully\n';
          }
          summary += '\n';
        }
      }

      if (result.wasCancelled) summary += '⚠️  Execution was cancelled\n';
    } else if (!command.iterationEnabled && isCommandResult(result)) {
      summary = '\nCommand completed\n';
      summary += `Exit Code: ${result.exitCode}\n`;
      summary += `Execution Time: ${result.executionTime}\n\n`;

      if (result.exitCode === 0) {
        summary += '✅ Success: Command executed successfully\n\n';
      } else if (result.exitCode === 128 && result.errorOutput?.includes('not a git repository')) {
        summary += 'ℹ️  Info: Directory is not a git repository\n';
        summary += "💡 Tip: Use 'git init' to initialize or navigate to a git repository\n\n";
      } else {
        summary += `⚠️  Warning: Command exited with code ${result.exitCode}\n\n`;
      }

      if (!result.output?.trim() && result.exitCode === 0) {
        summary += 'Output: (command completed successfully, no output)\n';
      }
      if (result.errorOutput?.trim()) summary += `\nErrors:\n${result.errorOutput}\n`;
      if (result.executionErrors?.length) summary += `\nExecution Errors:\n${result.executionErrors.join('\n')}\n`;
    }

    if (!command.iterationEnabled) {
      output.value += summary;
    } else if (summary) {
      output.value += `\n${summary}`;
    }

    if (!command.iterationEnabled && isCommandResult(result) && result.exitCode === 0) {
      showSuccessToast.value = true;
    } else if (command.iterationEnabled && isIterationResult(result) && result.failedItems === 0) {
      showSuccessToast.value = true;
    }

    if (!command.iterationEnabled && isCommandResult(result)) {
      store.addExecution(result);
    }
  } catch (error) {
    if (error instanceof DOMException && error.name === 'AbortError') {
      output.value += '\n[info] Execution stopped by user.\n';
      return;
    }

    const message = (error as Error)?.message || String(error) || 'Unknown error occurred';
    output.value = `Command execution failed:\n${message}\n\nTroubleshooting tips:\n• Check if the working directory exists\n• Verify the command is available in PATH\n• Ensure proper permissions\n• Try using absolute paths instead of ~\n`;
  } finally {
    isExecuting.value = false;
    abortController = null;
    lastProgressSnapshot = '';
  }
}

function handleStopExecution() {
  abortController?.abort();
}

function handleCommandChange(commandId: string) {
  if (!store.selectedProfile) return;
  const command = store.selectedProfile.commands.find((c) => c.id === commandId) ?? null;
  selectedCommand.value = command;
  showSuccessToast.value = false;

  if (command?.workingDirectory && !store.selectedDirectory) {
    const match = availableDirectories.value.find((d) => d.path === command.workingDirectory);
    if (match) store.setSelectedDirectory(match);
  }
}

function handleClearCommand() {
  selectedCommand.value = null;
}

function handleClearOutput() {
  output.value = '';
  showSuccessToast.value = false;
}

async function handleRetryApiConnection() {
  retryingApi.value = true;
  store.setError(null);
  await store.loadInitialData();
  retryingApi.value = false;
}

onMounted(() => {
  store.loadInitialData();
});

// Auto-select the first profile & its first command once profiles load.
watch(
  () => store.profiles,
  (profiles) => {
    if (profiles.length > 0 && !store.selectedProfile) {
      store.setSelectedProfile(profiles[0]);
      selectedCommand.value = profiles[0].commands[0] ?? null;
    }
  },
);

// Auto-select the command's working directory when it becomes available.
watch([selectedCommand, () => store.directories], () => {
  const workingDirectory = selectedCommand.value?.workingDirectory;
  if (!workingDirectory) return;
  const match = availableDirectories.value.find((d) => d.path === workingDirectory);
  if (match) store.setSelectedDirectory(match);
});

useKeyboardShortcuts({
  onExecute: handleExecuteCommand,
  onClearOutput: handleClearOutput,
  onToggleFocusMode: toggleFocusMode,
  onBrowseDirectory: handleBrowseClick,
  onOpenSettings: () => {
    settingsOpen.value = true;
  },
  canExecute: () => Boolean(selectedCommand.value) && !isExecuting.value,
});
</script>

<template>
  <div class="app" :class="{ 'app--focus': focusMode }">
    <header v-if="!focusMode" class="app__header">
      <h1 class="app__title">Command Runner</h1>
      <HeaderButtons :theme-mode="store.theme" @toggle-focus-mode="toggleFocusMode" @toggle-theme="toggleTheme" @settings-click="settingsOpen = true" />
    </header>

    <main class="app__main">
      <AlertBanner v-if="store.error" :message="store.error" :retrying="retryingApi" @retry="handleRetryApiConnection" />

      <section class="panel" :class="{ 'panel--compact': focusMode }">
        <div class="app__row">
          <ProfileSelector
            :profiles="store.profiles"
            :selected-profile="store.selectedProfile"
            @change="
              (profile) => {
                store.setSelectedProfile(profile);
                selectedCommand = profile?.commands[0] ?? null;
              }
            "
          />

          <DirectorySelector
            v-if="!focusMode"
            :directories="availableDirectories"
            :selected-directory="store.selectedDirectory"
            @change="store.setSelectedDirectory"
          />

          <div v-if="focusMode" class="app__row-header-buttons">
            <HeaderButtons :theme-mode="store.theme" @toggle-focus-mode="toggleFocusMode" @toggle-theme="toggleTheme" @settings-click="settingsOpen = true" />
          </div>
          <button v-else type="button" class="btn btn--outline" @click="handleBrowseClick">
            <AppIcon name="folder" /> Select Directory
          </button>
        </div>
      </section>

      <section class="panel" :class="{ 'panel--compact': focusMode }">
        <div class="app__row">
          <CommandSelector :selected-profile="store.selectedProfile" :selected-command="selectedCommand" @change="handleCommandChange" />
          <CommandControls
            :selected-command="selectedCommand"
            :is-executing="isExecuting"
            @execute="handleExecuteCommand"
            @stop="handleStopExecution"
            @clear="handleClearCommand"
          />
        </div>
      </section>

      <CommandDetails v-if="!focusMode && selectedCommand" :selected-command="selectedCommand" :selected-directory="store.selectedDirectory" />

      <CommandPreview v-if="selectedCommand" :selected-command="selectedCommand" :selected-directory="store.selectedDirectory" :focus-mode="focusMode" />

      <OutputPanel
        :output="output"
        :is-loading="isExecuting || store.isLoading"
        :focus-mode="focusMode"
        @clear="handleClearOutput"
        @copy="handleCopyOutput"
        @save="handleSaveLog"
      />
    </main>

    <ToastNotification :open="showSuccessToast" message="Command completed successfully!" @close="showSuccessToast = false" />

    <SettingsDialog :open="settingsOpen" @close="settingsOpen = false" />
  </div>
</template>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.app__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-3) var(--space-4);
  background-color: var(--color-bg-elevated);
  border-bottom: 1px solid var(--color-border);
  box-shadow: var(--shadow-sm);
}

.app__title {
  font-size: 1.125rem;
}

.app__main {
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
  padding: var(--space-4);
}

.app--focus .app__main {
  gap: var(--space-2);
}

.app__row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-3);
}

.app__row-header-buttons {
  display: flex;
  justify-content: center;
  flex: 1;
}
</style>

// src/CommandRunner.ReactWebsite/src/App.tsx
import { useState, useEffect, useRef } from 'react';
import {
  ThemeProvider,
  CssBaseline,
  Box,
  AppBar,
  Toolbar,
  Typography,
  Container,
  Paper,
  Button,
  Alert,
  Stack,
  Snackbar,
} from '@mui/material';
import {
  Folder,
  CheckCircle,
  Refresh,
  Error as ErrorIcon,
} from '@mui/icons-material';
import { useApp } from './contexts/AppContext';
import { commandsApi } from './services/api/commands';
import { CommandDto, CommandExecutionResponse, IterationExecutionResponse } from './services/api/types';
import { SettingsDialog } from './components/SettingsDialog';
import { ProfileSelector } from './components/ProfileSelector';
import { DirectorySelector } from './components/DirectorySelector';
import { CommandSelector } from './components/CommandSelector';
import { CommandControls } from './components/CommandControls';
import { CommandDetails } from './components/CommandDetails';
import { CommandPreview } from './components/CommandPreview';
import { OutputPanel } from './components/OutputPanel';
import HeaderButtons from './components/HeaderButtons';
import { getTheme } from './themes';

function App() {
  const { state, dispatch } = useApp();
  const [selectedCommand, setSelectedCommand] = useState<CommandDto | null>(null);
  const [isExecuting, setIsExecuting] = useState(false);
  const [output, setOutput] = useState<string>('');
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [focusMode, setFocusMode] = useState(false);
  const [showSuccessToast, setShowSuccessToast] = useState(false);
  const [retryingApi, setRetryingApi] = useState(false);
  const executionAbortControllerRef = useRef<AbortController | null>(null);
  const lastProgressSnapshotRef = useRef<string>('');

  const theme = getTheme(state.theme);

  const toggleTheme = () => {
    dispatch({ type: 'SET_THEME', payload: state.theme === 'light' ? 'dark' : 'light' });
  };

  const toggleFocusMode = () => {
    setFocusMode(!focusMode);
  };

  // Handle settings button click
  const handleSettingsClick = () => {
    setSettingsOpen(true);
  };

  // Handle browse button click - Use native dialog in Electron, fallback to prompt
  const handleBrowseClick = () => {
    // Check if running in Electron
    const isElectron = (window as any).electronAPI !== undefined;
    console.log('handleBrowseClick: isElectron detected:', isElectron);
    console.log('handleBrowseClick: window.electronAPI:', (window as any).electronAPI);

    if (isElectron) {
      try {
        (window as any).electronAPI.openDirectory().then((result: any) => {
          console.log('Directory dialog result:', result);
          if (!result.canceled && result.filePaths.length > 0) {
            const directoryPath = result.filePaths[0];
            const pathParts = directoryPath.split('/').filter((p: string) => p);
            const dirName = pathParts.length > 0 ? pathParts[pathParts.length - 1] : directoryPath;

            const newDirectory = {
              id: `dir-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
              path: directoryPath,
              name: dirName,
              createdAt: new Date().toISOString(),
              usageCount: 1,
            };

            // Check if directory already exists
            const existingDir = state.directories.find(d => d.path === directoryPath);
            if (existingDir) {
              dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: existingDir });
            } else {
              dispatch({ type: 'ADD_DIRECTORY', payload: newDirectory });
              dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: newDirectory });
            }
          }
        }).catch((error: any) => {
          console.error('Failed to open directory dialog:', error);
          // Fallback to prompt
          fallbackDirectorySelection();
        });
      } catch (error) {
        console.error('Failed to call electronAPI:', error);
        // Fallback to prompt
        fallbackDirectorySelection();
      }
    } else {
      // Web fallback
      fallbackDirectorySelection();
    }
  };

  // Fallback directory selection for web or when Electron dialog fails
  const fallbackDirectorySelection = () => {
    const directoryPath = prompt('Enter directory path:', state.selectedDirectory?.path || '~/');

    if (directoryPath && directoryPath.trim()) {
      const path = directoryPath.trim();
      const pathParts = path.split('/').filter(p => p);
      const dirName = pathParts.length > 0 ? pathParts[pathParts.length - 1] : path;

      const newDirectory = {
        id: `dir-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        path: path,
        name: dirName,
        createdAt: new Date().toISOString(),
        usageCount: 1,
      };

      // Check if directory already exists
      const existingDir = state.directories.find(d => d.path === path);
      if (existingDir) {
        dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: existingDir });
      } else {
        dispatch({ type: 'ADD_DIRECTORY', payload: newDirectory });
        dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: newDirectory });
      }
    }
  };

  // Get all available directories including command's working directory
  const getAvailableDirectories = () => {
    const directories = [...state.directories];

    // Add the current command's working directory if it exists and isn't already in the list
    if (selectedCommand?.workingDirectory) {
      const commandDirExists = directories.some(d => d.path === selectedCommand.workingDirectory);
      if (!commandDirExists) {
        const pathParts = selectedCommand.workingDirectory.split('/').filter(p => p);
        const dirName = pathParts.length > 0 ? pathParts[pathParts.length - 1] : selectedCommand.workingDirectory;

        directories.push({
          id: `cmd-dir-${selectedCommand.id}`,
          path: selectedCommand.workingDirectory,
          name: dirName,
          createdAt: new Date().toISOString(),
          usageCount: 0,
        });
      }
    }

    return directories;
  };

  // Handle copy output
  const handleCopyOutput = () => {
    navigator.clipboard.writeText(output);
  };

  // Handle save log
  const handleSaveLog = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `command-output-${new Date().toISOString().slice(0, 19)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Handle command execution
  const handleExecuteCommand = async () => {
    if (!selectedCommand || !state.selectedProfile) return;

    if (executionAbortControllerRef.current) {
      executionAbortControllerRef.current.abort();
    }

    const abortController = new AbortController();
    executionAbortControllerRef.current = abortController;
    lastProgressSnapshotRef.current = '';

    // Check if command requires confirmation
    if (selectedCommand.requireConfirmation) {
      const confirmed = window.confirm(
        `This command requires confirmation:\n\n${selectedCommand.name}\n${selectedCommand.executable} ${selectedCommand.arguments}\n\nWorking Directory: ${state.selectedDirectory?.path || selectedCommand.workingDirectory || '~/'}\n\nDo you want to proceed?`
      );
      if (!confirmed) {
        return; // User cancelled
      }
    }

    setIsExecuting(true);
    const workingDirectory = state.selectedDirectory?.path || selectedCommand.workingDirectory || '~/';

    if (selectedCommand.iterationEnabled) {
      setOutput(`Executing iteratively: ${selectedCommand.executable} ${selectedCommand.arguments}\nWorking Directory: ${workingDirectory}\nScanning subdirectories...\n\n`);
    } else {
      setOutput(`Executing: ${selectedCommand.executable} ${selectedCommand.arguments}\nWorking Directory: ${workingDirectory}\n\n`);
    }

    try {
      const request = {
        commandId: selectedCommand.id,
        profileId: state.selectedProfile.id,
        workingDirectory: workingDirectory,
        userConfirmed: selectedCommand.requireConfirmation,
      };

      console.log('Executing command:', request);

      let result;
      if (selectedCommand.iterationEnabled) {
        const iterativeRequest = {
          ...request,
          iterationOptions: {
            maxDepth: 1,
            includeRootDirectory: false,
            skipErrors: true,
            stopOnFirstFailure: false,
            excludePatterns: [],
            includePatterns: [],
            maxParallelism: 1
          }
        };
        result = await commandsApi.executeIterativeCommandWithStreaming(iterativeRequest, {
          onItemStart: (itemPath) => {
            const dirName = itemPath.split(/[\\/]/).filter(Boolean).pop() || itemPath;
            setOutput((previous) => `${previous}\n▶ Processing ${dirName}\n`);
          },
          onStdout: (itemPath, line) => {
            const dirName = itemPath.split(/[\\/]/).filter(Boolean).pop() || itemPath;
            setOutput((previous) => `${previous}[${dirName}] ${line}\n`);
          },
          onStderr: (itemPath, line) => {
            const dirName = itemPath.split(/[\\/]/).filter(Boolean).pop() || itemPath;
            setOutput((previous) => `${previous}[${dirName}][stderr] ${line}\n`);
          },
          onProgress: (progress) => {
            const snapshot = `${progress.processedItems}/${progress.totalItems}:${progress.successfulItems}:${progress.failedItems}:${progress.skippedItems}`;

            if (lastProgressSnapshotRef.current === snapshot) {
              return;
            }

            lastProgressSnapshotRef.current = snapshot;
            setOutput((previous) => `${previous}[progress] ${progress.processedItems}/${progress.totalItems} (ok: ${progress.successfulItems}, failed: ${progress.failedItems}, skipped: ${progress.skippedItems})\n`);
          },
          onError: (message) => {
            setOutput((previous) => `${previous}[error] ${message}\n`);
          }
        }, abortController.signal);
      } else {
        result = await commandsApi.executeCommandWithStreaming(request, {
          onStdout: (line) => {
            setOutput((previous) => `${previous}${line}\n`);
          },
          onStderr: (line) => {
            setOutput((previous) => `${previous}[stderr] ${line}\n`);
          },
          onError: (message) => {
            setOutput((previous) => `${previous}[error] ${message}\n`);
          }
        }, abortController.signal);
      }

      let outputText = '';

      // Type guard to check if result is IterationExecutionResponse
      const isIterationResult = (res: any): res is IterationExecutionResponse =>
        res && typeof res.totalItems === 'number';

      // Type guard to check if result is CommandExecutionResponse
      const isCommandResult = (res: any): res is CommandExecutionResponse =>
        res && typeof res.exitCode === 'number';

      if (selectedCommand.iterationEnabled && isIterationResult(result)) {
        // Handle iterative execution results
        outputText = `Iterative execution completed\n`;
        outputText += `Total Items: ${result.totalItems}\n`;
        outputText += `Successful: ${result.successfulItems}\n`;
        outputText += `Failed: ${result.failedItems}\n`;
        outputText += `Skipped: ${result.skippedItems}\n`;
        outputText += `Execution Time: ${result.startedAt} - ${result.completedAt || 'In Progress'}\n\n`;

        if (result.itemResults && result.itemResults.length > 0) {
          outputText += `Results by directory:\n\n`;
          result.itemResults.forEach((item) => {
            const status = item.wasSuccessful ? '✅' : '❌';
            const dirName = item.itemPath.split('/').pop() || item.itemPath;
            outputText += `${status} ${dirName}/\n`;

            // Show command output if available
            if (item.output && item.output.trim()) {
              outputText += `   Output: ${item.output.trim()}\n`;
            }

            if (item.errorOutput && item.errorOutput.trim()) {
              outputText += `   Error: ${item.errorOutput.trim()}\n`;
            }

            if (item.executionTime) {
              outputText += `   Execution time: ${item.executionTime}\n`;
            }

            if (!item.wasSuccessful && item.errorMessage) {
              outputText += `   Error: ${item.errorMessage}\n`;
            } else if (item.wasSuccessful && !item.output?.trim() && !item.errorOutput?.trim()) {
              outputText += `   Status: Command completed successfully\n`;
            }

            outputText += '\n';
          });
        }

        if (result.wasCancelled) {
          outputText += `⚠️  Execution was cancelled\n`;
        }
      } else if (!selectedCommand.iterationEnabled && isCommandResult(result)) {
        outputText = `\nCommand completed\n`;
        outputText += `Exit Code: ${result.exitCode}\n`;
        outputText += `Execution Time: ${result.executionTime}\n\n`;

        // Provide helpful interpretation of exit codes
        if (result.exitCode === 0) {
          outputText += `✅ Success: Command executed successfully\n\n`;
        } else if (result.exitCode === 128 && result.errorOutput?.includes('not a git repository')) {
          outputText += `ℹ️  Info: Directory is not a git repository\n`;
          outputText += `💡 Tip: Use 'git init' to initialize or navigate to a git repository\n\n`;
        } else if (result.exitCode !== 0) {
          outputText += `⚠️  Warning: Command exited with code ${result.exitCode}\n\n`;
        }

        if (!result.output?.trim() && result.exitCode === 0) {
          outputText += `Output: (command completed successfully, no output)\n`;
        }

        if (result.errorOutput && result.errorOutput.trim()) {
          outputText += `\nErrors:\n${result.errorOutput}\n`;
        }

        // Show execution errors if any
        if (result.executionErrors && result.executionErrors.length > 0) {
          outputText += `\nExecution Errors:\n${result.executionErrors.join('\n')}\n`;
        }
      }

      if (!selectedCommand.iterationEnabled) {
        setOutput((previous) => `${previous}${outputText}`);
      } else if (outputText) {
        setOutput((previous) => `${previous}\n${outputText}`);
      }

      // Set success status for successful command completion
      if (!selectedCommand.iterationEnabled && isCommandResult(result) && result.exitCode === 0) {
        setShowSuccessToast(true);
      } else if (selectedCommand.iterationEnabled && isIterationResult(result) && result.failedItems === 0) {
        setShowSuccessToast(true);
      }

      // Add to execution history (only for command results, not iteration results)
      if (!selectedCommand.iterationEnabled && isCommandResult(result)) {
        dispatch({ type: 'ADD_EXECUTION', payload: result as CommandExecutionResponse });
      }
    } catch (error) {
      if (error instanceof DOMException && error.name === 'AbortError') {
        setOutput((previous) => `${previous}\n[info] Execution stopped by user.\n`);
        return;
      }

      const errorMessage = (error as any)?.message || String(error) || 'Unknown error occurred';
      console.error('Command execution error:', error);
      setOutput(`Command execution failed:\n${errorMessage}\n\nTroubleshooting tips:\n• Check if the working directory exists\n• Verify the command is available in PATH\n• Ensure proper permissions\n• Try using absolute paths instead of ~\n`);
      // Error status is handled by the error display
    } finally {
      setIsExecuting(false);
      executionAbortControllerRef.current = null;
      lastProgressSnapshotRef.current = '';
    }
  };

  const handleStopExecution = () => {
    if (executionAbortControllerRef.current) {
      executionAbortControllerRef.current.abort();
    }
  };

  // Handle command selection
  const handleCommandChange = (commandId: string) => {
    if (!state.selectedProfile) return;

    const command = state.selectedProfile.commands.find(c => c.id === commandId);
    setSelectedCommand(command || null);
    setShowSuccessToast(false); // Hide any existing success toast

    // Auto-select the command's working directory if available and no directory is selected
    if (command?.workingDirectory && !state.selectedDirectory) {
      const availableDirs = getAvailableDirectories();
      const commandDir = availableDirs.find(d => d.path === command.workingDirectory);
      if (commandDir) {
        dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: commandDir });
      }
    }
  };

  // Auto-select first profile and command on initial load
  useEffect(() => {
    if (state.profiles.length > 0 && !state.selectedProfile) {
      const firstProfile = state.profiles[0];
      dispatch({ type: 'SET_SELECTED_PROFILE', payload: firstProfile });
      if (firstProfile.commands.length > 0) {
        setSelectedCommand(firstProfile.commands[0]);
      }
    }
  }, [state.profiles, state.selectedProfile, dispatch]);

  // Auto-select directory when command changes
  useEffect(() => {
    if (selectedCommand?.workingDirectory) {
      const availableDirs = getAvailableDirectories();
      const commandDir = availableDirs.find(d => d.path === selectedCommand.workingDirectory);
      if (commandDir) {
        dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: commandDir });
      }
    }
  }, [selectedCommand, state.directories]);

  // Keyboard shortcuts for desktop experience
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Only handle shortcuts when not typing in input fields
      if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) {
        return;
      }

      // Ctrl+Enter or Cmd+Enter to execute command
      if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') {
        event.preventDefault();
        if (selectedCommand && !isExecuting) {
          handleExecuteCommand();
        }
      }

      // Ctrl+L or Cmd+L to clear output
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'l') {
        event.preventDefault();
        handleClearOutput();
      }

      // F11 to toggle focus mode
      if (event.key === 'F11') {
        event.preventDefault();
        toggleFocusMode();
      }

      // Ctrl+B or Cmd+B to browse directory
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'b') {
        event.preventDefault();
        handleBrowseClick();
      }

      // Ctrl+, or Cmd+, to open settings
      if ((event.ctrlKey || event.metaKey) && event.key === ',') {
        event.preventDefault();
        setSettingsOpen(true);
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [selectedCommand, isExecuting]);

  // Clear selected command
  const handleClearCommand = () => {
    setSelectedCommand(null);
  };

  // Clear output
  const handleClearOutput = () => {
    setOutput('');
    setShowSuccessToast(false);
  };

  // Retry API connection
  const handleRetryApiConnection = async () => {
    console.log('🔄 Retrying API connection...');
    setRetryingApi(true);
    dispatch({ type: 'SET_ERROR', payload: null });

    try {
      // Import the API services
      const { profilesApi, directoriesApi } = await import('./services/api');

      // Try to load data again
      const [profiles, directories] = await Promise.all([
        profilesApi.getAllProfiles(),
        directoriesApi.getAllDirectories()
      ]);

      console.log('✅ API retry successful - Profiles:', profiles.length, 'Directories:', directories.length);

      const profilesWithIds = profiles.map(profile => ({
        ...profile,
        id: profile.id || `profile-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
      }));

      dispatch({ type: 'SET_PROFILES', payload: profilesWithIds });
      dispatch({ type: 'SET_DIRECTORIES', payload: directories });

    } catch (error) {
      console.warn('❌ API retry failed:', error);
      const err = error as any;
      let errorMessage = 'Unable to connect to Command Runner API';
      let errorDetails = '';

      if (err.code === 'ECONNREFUSED') {
        errorMessage = 'API server is not running';
        errorDetails = 'Please ensure the Command Runner API is started. In development, run the API project. In production, the API should start automatically.';
      } else if (err.code === 'ENOTFOUND') {
        errorMessage = 'API server not found';
        errorDetails = 'The API server may not be running or the connection URL is incorrect.';
      } else if (err.response) {
        errorMessage = `API server error (${err.response.status})`;
        errorDetails = err.response.data?.message || err.response.statusText || 'Unknown server error';
      } else if (err.request) {
        errorMessage = 'Network connection failed';
        errorDetails = 'Please check your internet connection and ensure the API server is accessible.';
      }

      const fullErrorMessage = errorDetails
        ? `${errorMessage}\n\n${errorDetails}`
        : errorMessage;

      dispatch({ type: 'SET_ERROR', payload: fullErrorMessage });
    } finally {
      setRetryingApi(false);
    }
  };


  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', bgcolor: 'background.default' }}>
        {/* Top Toolbar - Hidden in focus mode */}
        {!focusMode && (
          <AppBar position="static" sx={{
            width: '100%',
            backgroundColor: theme.palette.mode === 'dark' ? '#1e293b' : '#ffffff',
            borderBottom: `1px solid ${theme.palette.mode === 'dark' ? '#334155' : '#e2e8f0'}`,
            boxShadow: theme.palette.mode === 'dark'
              ? '0 1px 3px rgba(0, 0, 0, 0.3)'
              : '0 1px 3px rgba(0, 0, 0, 0.1)',
          }}>
            <Toolbar sx={{ minHeight: 56, px: 2 }}>
              <Typography variant="h6" component="div" sx={{
                flexGrow: 1,
                fontWeight: 600,
                color: theme.palette.text.primary,
              }}>
                Command Runner
              </Typography>
              <Box sx={{ display: 'flex', gap: 1 }}>
                <HeaderButtons
                  themeMode={state.theme}
                  onToggleFocusMode={toggleFocusMode}
                  onToggleTheme={toggleTheme}
                  onSettingsClick={handleSettingsClick}
                />
              </Box>
            </Toolbar>
          </AppBar>
        )}

        <Container maxWidth={false} sx={{ flexGrow: 1, py: 2, px: { xs: 2, md: 4 } }}>
          {state.error && (
            <Alert
              severity="error"
              sx={{ mb: 2 }}
              icon={<ErrorIcon />}
              action={
                <Button
                  color="inherit"
                  size="small"
                  onClick={handleRetryApiConnection}
                  disabled={retryingApi}
                  startIcon={retryingApi ? undefined : <Refresh />}
                  sx={{ minWidth: 'auto' }}
                >
                  {retryingApi ? 'Retrying...' : 'Retry'}
                </Button>
              }
            >
              <Box sx={{ mb: 1 }}>
                <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>
                  API Connection Error
                </Typography>
                <Typography variant="body2" sx={{ whiteSpace: 'pre-line' }}>
                  {state.error}
                </Typography>
              </Box>
            </Alert>
          )}

          <Stack spacing={2}>
            {/* Profile and Directory Selection */}
            <Paper sx={{ p: focusMode ? 0.5 : 2, mb: focusMode ? 0.5 : 2 }}>
              <Box sx={{
                display: 'flex',
                flexDirection: { xs: 'column', md: 'row' },
                gap: focusMode ? 1 : 2,
                alignItems: 'center',
                flexWrap: 'wrap'
              }}>
                <ProfileSelector
                  profiles={state.profiles}
                  selectedProfile={state.selectedProfile}
                  onProfileChange={(profile) => {
                    dispatch({ type: 'SET_SELECTED_PROFILE', payload: profile });
                    // Select first command of the new profile
                    if (profile && profile.commands.length > 0) {
                      setSelectedCommand(profile.commands[0]);
                    } else {
                      setSelectedCommand(null);
                    }
                  }}
                  size={focusMode ? "small" : "medium"}
                />

                {!focusMode && (
                  <DirectorySelector
                    directories={getAvailableDirectories()}
                    selectedDirectory={state.selectedDirectory}
                    onDirectoryChange={(directory) => {
                      dispatch({ type: 'SET_SELECTED_DIRECTORY', payload: directory });
                    }}
                    size="medium"
                  />
                )}

                {focusMode ? (
                  <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center', justifyContent: 'center', flex: 1 }}>
                    <HeaderButtons
                      themeMode={state.theme}
                      onToggleFocusMode={toggleFocusMode}
                      onToggleTheme={toggleTheme}
                      onSettingsClick={handleSettingsClick}
                    />
                  </Box>
                ) : (
                  <Button
                    variant="outlined"
                    startIcon={<Folder />}
                    onClick={handleBrowseClick}
                    sx={{ minWidth: 120 }}
                    size="small"
                  >
                    Select Directory
                  </Button>
                )}
              </Box>
            </Paper>

            {/* Command Selection and Controls */}
            <Paper sx={{ p: focusMode ? 0.5 : 2, mb: focusMode ? 0.5 : 2 }}>
              <Box sx={{
                display: 'flex',
                flexDirection: { xs: 'column', md: 'row' },
                gap: focusMode ? 1 : 2,
                alignItems: 'center',
                flexWrap: 'wrap'
              }}>
                <CommandSelector
                  selectedProfile={state.selectedProfile}
                  selectedCommand={selectedCommand}
                  onCommandChange={handleCommandChange}
                  size={focusMode ? "small" : "medium"}
                />

                <CommandControls
                  selectedCommand={selectedCommand}
                  isExecuting={isExecuting}
                  focusMode={focusMode}
                  onExecute={handleExecuteCommand}
                  onStop={handleStopExecution}
                  onClear={handleClearCommand}
                />
              </Box>
            </Paper>

            {/* Command Details */}
            {!focusMode && (
              <CommandDetails
                selectedCommand={selectedCommand}
                selectedDirectory={state.selectedDirectory}
              />
            )}

            {/* Command Preview */}
            {selectedCommand && (
              <CommandPreview
                selectedCommand={selectedCommand}
                selectedDirectory={state.selectedDirectory}
                focusMode={focusMode}
              />
            )}

            {/* Output Window */}
            <OutputPanel
              output={output}
              isLoading={isExecuting || state.isLoading}
              focusMode={focusMode}
              onClear={handleClearOutput}
              onCopy={handleCopyOutput}
              onSave={handleSaveLog}
            />
          </Stack>
        </Container>
      </Box>

      {/* Success Toast */}
      <Snackbar
        open={showSuccessToast}
        autoHideDuration={3000}
        onClose={() => setShowSuccessToast(false)}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert
          onClose={() => setShowSuccessToast(false)}
          severity="success"
          variant="filled"
          icon={<CheckCircle fontSize="inherit" />}
          sx={{
            fontWeight: 500,
            opacity: 0.9,
            boxShadow: theme.palette.mode === 'dark'
              ? '0 4px 12px rgba(0, 0, 0, 0.2)'
              : '0 4px 12px rgba(0, 0, 0, 0.08)',
          }}
        >
          Command completed successfully!
        </Alert>
      </Snackbar>

      {/* Settings Dialog */}
      <SettingsDialog
        open={settingsOpen}
        onClose={() => setSettingsOpen(false)}
      />
    </ThemeProvider>
  );
}

export default App;
