// src/CommandRunner.Website.VueJs/src/components/CommandDetails.vue
<script setup lang="ts">
import type { CommandDto, FavoriteDirectoryDto } from '../services/api';

defineProps<{
  selectedCommand: CommandDto;
  selectedDirectory: FavoriteDirectoryDto | null;
}>();
</script>

<template>
  <section class="panel command-details" aria-labelledby="command-details-heading">
    <div class="command-details__header">
      <h2 id="command-details-heading" class="command-details__title">Command Details</h2>
      <div class="command-details__badges">
        <span
          v-if="selectedCommand.iterationEnabled"
          class="chip chip--info"
          title="This command runs in subdirectories recursively"
        >
          🔄 Iterative
        </span>
        <span
          v-if="selectedCommand.requireConfirmation"
          class="chip chip--warning"
          title="This command will ask for confirmation before running"
        >
          ⚠️ Requires Confirmation
        </span>
      </div>
    </div>

    <div class="command-details__grid">
      <div class="field">
        <label class="field__label" for="detail-executable">Executable</label>
        <input
          id="detail-executable"
          class="field__control field__control--readonly"
          type="text"
          readonly
          tabindex="-1"
          :value="selectedCommand.executable"
        />
      </div>
      <div class="field">
        <label class="field__label" for="detail-arguments">Arguments</label>
        <input
          id="detail-arguments"
          class="field__control field__control--readonly"
          type="text"
          readonly
          tabindex="-1"
          :value="selectedCommand.arguments"
        />
      </div>
      <div class="field">
        <label class="field__label" for="detail-working-dir">Working Directory</label>
        <input
          id="detail-working-dir"
          class="field__control field__control--readonly"
          type="text"
          readonly
          tabindex="-1"
          :value="selectedDirectory?.path || selectedCommand.workingDirectory || ''"
        />
      </div>
      <div class="field">
        <label class="field__label" for="detail-shell">Shell</label>
        <input
          id="detail-shell"
          class="field__control field__control--readonly"
          type="text"
          readonly
          tabindex="-1"
          :value="selectedCommand.shell || ''"
        />
      </div>
    </div>
  </section>
</template>

<style scoped>
.command-details__header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: var(--space-4);
  gap: var(--space-2);
}

.command-details__title {
  font-size: 1.05rem;
}

.command-details__badges {
  display: flex;
  gap: var(--space-2);
  flex-wrap: wrap;
}

.command-details__grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: var(--space-4);
}
</style>

// src/CommandRunner.ReactWebsite/src/components/CommandDetails.tsx
import React from 'react';
import { Paper, Typography, Stack, TextField, Box, Chip } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import { CommandDto, FavoriteDirectoryDto } from '../services/api';

interface CommandDetailsProps {
  selectedCommand: CommandDto | null;
  selectedDirectory: FavoriteDirectoryDto | null;
}

export const CommandDetails: React.FC<CommandDetailsProps> = ({
  selectedCommand,
  selectedDirectory
}) => {
  const theme = useTheme();

  if (!selectedCommand) return null;

  return (
    <Paper sx={{ p: 2 }}>
      {/* Header with Properties */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
        <Typography variant="h6">
          Command Details
        </Typography>
        <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', ml: 2 }}>
          {selectedCommand.iterationEnabled && (
            <Chip
              label="🔄 Iterative"
              size="small"
              color="info"
              variant="outlined"
              title="This command runs in subdirectories recursively"
            />
          )}
          {selectedCommand.requireConfirmation && (
            <Chip
              label="⚠️ Requires Confirmation"
              size="small"
              color="warning"
              variant="outlined"
              title="This command will ask for confirmation before running"
            />
          )}
        </Box>
      </Box>

      <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
        <Stack spacing={2} sx={{ flex: 1 }}>
          <TextField
            fullWidth
            size="small"
            label="Executable"
            value={selectedCommand.executable}
            variant="filled"
            slotProps={{
              input: {
                readOnly: true,
                sx: {
                  cursor: 'not-allowed',
                  '& .MuiInputBase-input': {
                    color: theme.palette.text.disabled,
                  },
                  '& .MuiFilledInput-root': {
                    '&::before': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                    '&::after': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                  },
                }
              }
            }}
          />
          <TextField
            fullWidth
            size="small"
            label="Arguments"
            value={selectedCommand.arguments}
            variant="filled"
            slotProps={{
              input: {
                readOnly: true,
                sx: {
                  cursor: 'not-allowed',
                  '& .MuiInputBase-input': {
                    color: theme.palette.text.disabled,
                  },
                  '& .MuiFilledInput-root': {
                    '&::before': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                    '&::after': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                  },
                }
              }
            }}
          />
        </Stack>
        <Stack spacing={2} sx={{ flex: 1 }}>
          <TextField
            fullWidth
            size="small"
            label="Working Directory"
            value={selectedDirectory?.path || selectedCommand.workingDirectory || ''}
            variant="filled"
            slotProps={{
              input: {
                readOnly: true,
                sx: {
                  cursor: 'not-allowed',
                  '& .MuiInputBase-input': {
                    color: theme.palette.text.disabled,
                  },
                  '& .MuiFilledInput-root': {
                    '&::before': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                    '&::after': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                  },
                }
              }
            }}
          />
          <TextField
            fullWidth
            size="small"
            label="Shell"
            value={selectedCommand.shell || ''}
            variant="filled"
            slotProps={{
              input: {
                readOnly: true,
                sx: {
                  cursor: 'not-allowed',
                  '& .MuiInputBase-input': {
                    color: theme.palette.text.disabled,
                  },
                  '& .MuiFilledInput-root': {
                    '&::before': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                    '&::after': {
                      borderBottomStyle: 'dashed',
                      borderBottomColor: theme.palette.action.disabled,
                    },
                  },
                }
              }
            }}
          />
        </Stack>
      </Stack>
    </Paper>
  );
};
