// src/CommandRunner.ReactWebsite/src/components/CommandPreview.tsx
import React from 'react';
import { Paper, Typography, Box, useTheme } from '@mui/material';
import { CommandDto, FavoriteDirectoryDto } from '../services/api';

interface CommandPreviewProps {
  selectedCommand: CommandDto | null;
  selectedDirectory: FavoriteDirectoryDto | null;
  focusMode: boolean;
}

export const CommandPreview: React.FC<CommandPreviewProps> = ({
  selectedCommand,
  selectedDirectory,
  focusMode
}) => {
  const theme = useTheme();

  if (!selectedCommand) return null;

  if (focusMode) {
    // Plain text in focus mode
    return (
      <Box sx={{ mb: 0.5, px: 0.5, width: '100%', maxWidth: '100%' }}>
        <Typography
          variant="body2"
          sx={{
            fontFamily: 'monospace',
            fontSize: '0.7rem',
            color: theme.palette.text.secondary,
            wordWrap: 'break-word',
            overflowWrap: 'break-word',
            lineHeight: 1.1,
            opacity: 0.8,
            whiteSpace: 'pre-wrap'
          }}
        >
          <Box component="span" sx={{ color: theme.palette.success.main }}>
            {selectedDirectory?.path || selectedCommand.workingDirectory || '~/'}
          </Box>
          {' $ '}
          <Box component="span" sx={{ color: theme.palette.primary.main, fontWeight: 'bold' }}>
            {selectedCommand.executable} {selectedCommand.arguments}
          </Box>
        </Typography>
      </Box>
    );
  }

  // Proper tile in normal mode
  return (
    <Box sx={{ width: '100%', maxWidth: '100%' }}>
      <Paper sx={{ p: 2, mb: 2 }}>
        <Typography variant="h6" gutterBottom>
          Command Preview
        </Typography>
        <Box sx={{
          p: 2,
          backgroundColor: theme.palette.mode === 'dark' ? '#1e293b' : '#ffffff',
          borderRadius: 1,
          border: `1px solid ${theme.palette.mode === 'dark' ? '#334155' : '#e2e8f0'}`,
          boxShadow: theme.palette.mode === 'dark'
            ? '0 1px 3px rgba(0, 0, 0, 0.3)'
            : '0 1px 3px rgba(0, 0, 0, 0.1)',
          fontFamily: '"SF Mono", "Monaco", "Inconsolata", "Fira Code", monospace',
          fontSize: '0.875rem',
          color: theme.palette.text.primary,
          position: 'relative',
          wordWrap: 'break-word',
          overflowWrap: 'break-word',
          '&::before': {
            content: '""',
            position: 'absolute',
            top: 12,
            left: 16,
            width: 6,
            height: 6,
            borderRadius: '50%',
            backgroundColor: '#10b981',
          }
        }}>
          <Box sx={{ pl: 3 }}>
            <Typography component="div" sx={{
              fontFamily: 'inherit',
              fontSize: 'inherit',
              color: 'inherit',
              wordWrap: 'break-word',
              overflowWrap: 'break-word',
              lineHeight: 1.4,
              whiteSpace: 'pre-wrap'
            }}>
              <Box component="span" sx={{ color: '#10b981' }}>
                {selectedDirectory?.path || selectedCommand.workingDirectory || '~/'}
              </Box>
              <Box component="span" sx={{ color: theme.palette.text.secondary, mx: 0.5 }}>
                {' $ '}
              </Box>
              <Box component="span" sx={{ color: '#2563eb', fontWeight: 'bold' }}>
                {selectedCommand.executable}
              </Box>
              {selectedCommand.arguments && (
                <Box component="span" sx={{ color: '#64748b', ml: 0.5 }}>
                  {selectedCommand.arguments}
                </Box>
              )}
            </Typography>
          </Box>
        </Box>
      </Paper>
    </Box>
  );
};

// src/CommandRunner.Website.VueJs/src/components/CommandPreview.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { CommandDto, FavoriteDirectoryDto } from '../services/api';

const props = defineProps<{
  selectedCommand: CommandDto;
  selectedDirectory: FavoriteDirectoryDto | null;
  focusMode: boolean;
}>();

const workingDirectory = computed(() => props.selectedDirectory?.path || props.selectedCommand.workingDirectory || '~/');
</script>

<template>
  <div v-if="focusMode" class="command-preview command-preview--focus">
    <p class="command-preview__line">
      <span class="command-preview__cwd">{{ workingDirectory }}</span>
      <span class="command-preview__prompt"> $ </span>
      <span class="command-preview__cmd">{{ selectedCommand.executable }} {{ selectedCommand.arguments }}</span>
    </p>
  </div>

  <section v-else class="panel command-preview" aria-labelledby="command-preview-heading">
    <h2 id="command-preview-heading" class="command-preview__title">Command Preview</h2>
    <div class="command-preview__terminal">
      <span class="command-preview__dot" aria-hidden="true"></span>
      <p class="command-preview__line">
        <span class="command-preview__cwd">{{ workingDirectory }}</span>
        <span class="command-preview__prompt"> $ </span>
        <span class="command-preview__cmd">{{ selectedCommand.executable }}</span>
        <span v-if="selectedCommand.arguments" class="command-preview__args"> {{ selectedCommand.arguments }}</span>
      </p>
    </div>
  </section>
</template>

<style scoped>
.command-preview--focus {
  padding: 0 var(--space-1);
  margin-bottom: var(--space-1);
}

.command-preview--focus .command-preview__line {
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: var(--color-text-secondary);
  opacity: 0.85;
  white-space: pre-wrap;
  word-break: break-word;
  margin: 0;
}

.command-preview__title {
  font-size: 1.05rem;
  margin-bottom: var(--space-3);
}

.command-preview__terminal {
  position: relative;
  padding: var(--space-3) var(--space-3) var(--space-3) var(--space-6);
  background-color: var(--color-bg-inset);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-sm);
  font-family: var(--font-mono);
  font-size: 0.875rem;
}

.command-preview__dot {
  position: absolute;
  top: 14px;
  left: 16px;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background-color: var(--color-success);
}

.command-preview__line {
  margin: 0;
  line-height: 1.4;
  white-space: pre-wrap;
  word-break: break-word;
}

.command-preview__cwd {
  color: var(--color-success);
}

.command-preview__prompt {
  color: var(--color-text-secondary);
}

.command-preview__cmd {
  color: var(--color-primary);
  font-weight: bold;
}

.command-preview__args {
  color: var(--color-text-secondary);
}
</style>
