// src/CommandRunner.ReactWebsite/src/components/CommandSelector.tsx
import React from 'react';
import { FormControl, InputLabel, Select, MenuItem, SelectChangeEvent } from '@mui/material';
import { CommandDto, ProfileDto } from '../services/api';

interface CommandSelectorProps {
  selectedProfile: ProfileDto | null;
  selectedCommand: CommandDto | null;
  onCommandChange: (commandId: string) => void;
  size?: 'small' | 'medium';
}

const CommandSelectorComponent: React.FC<CommandSelectorProps> = ({
  selectedProfile,
  selectedCommand,
  onCommandChange,
  size = 'medium'
}) => {
  const handleChange = (event: SelectChangeEvent<string>) => {
    onCommandChange(event.target.value);
  };

  return (
    <FormControl size={size} sx={{ width: { xs: '100%', sm: 280, md: 320 } }}>
      <InputLabel>Command</InputLabel>
      <Select
        value={selectedCommand?.id || ''}
        label="Command"
        disabled={!selectedProfile}
        variant="filled"
        onChange={handleChange}
        sx={{
          '& .MuiSelect-select': {
            whiteSpace: 'normal',
            wordWrap: 'break-word',
            lineHeight: 1.2,
            maxHeight: '3em',
            overflow: 'hidden',
          }
        }}
      >
        {!selectedProfile ? (
          <MenuItem disabled>Select a profile first</MenuItem>
        ) : selectedProfile.commands.length === 0 ? (
          <MenuItem disabled>No commands in this profile</MenuItem>
        ) : (
          selectedProfile.commands.map((command) => (
            <MenuItem key={command.id} value={command.id}>
              {command.name}
            </MenuItem>
          ))
        )}
      </Select>
    </FormControl>
  );
};

export const CommandSelector = React.memo(CommandSelectorComponent);

// src/CommandRunner.Website.VueJs/src/components/CommandSelector.vue
<script setup lang="ts">
import type { CommandDto, ProfileDto } from '../services/api';

defineProps<{
  selectedProfile: ProfileDto | null;
  selectedCommand: CommandDto | null;
}>();

const emit = defineEmits<{
  change: [commandId: string];
}>();

function handleChange(event: Event) {
  emit('change', (event.target as HTMLSelectElement).value);
}
</script>

<template>
  <div class="field command-selector">
    <label class="field__label" for="command-selector">Command</label>
    <select
      id="command-selector"
      class="field__control"
      :disabled="!selectedProfile"
      :value="selectedCommand?.id ?? ''"
      @change="handleChange"
    >
      <option v-if="!selectedProfile" value="" disabled>Select a profile first</option>
      <option v-else-if="selectedProfile.commands.length === 0" value="" disabled>
        No commands in this profile
      </option>
      <option v-for="command in selectedProfile?.commands ?? []" :key="command.id" :value="command.id">
        {{ command.name }}
      </option>
    </select>
  </div>
</template>

<style scoped>
.command-selector {
  width: 100%;
  max-width: 320px;
}
</style>
