// src/CommandRunner.ReactWebsite/src/components/DirectorySelector.tsx
import React from 'react';
import { FormControl, InputLabel, Select, MenuItem, SelectChangeEvent } from '@mui/material';
import { FavoriteDirectoryDto } from '../services/api';

interface DirectorySelectorProps {
  directories: FavoriteDirectoryDto[];
  selectedDirectory: FavoriteDirectoryDto | null;
  onDirectoryChange: (directory: FavoriteDirectoryDto | null) => void;
  size?: 'small' | 'medium';
}

const DirectorySelectorComponent: React.FC<DirectorySelectorProps> = ({
  directories,
  selectedDirectory,
  onDirectoryChange,
  size = 'medium'
}) => {
  const handleChange = (event: SelectChangeEvent<string>) => {
    const directoryId = event.target.value;
    const directory = directories.find(d => d.id === directoryId) || null;
    onDirectoryChange(directory);
  };

  return (
    <FormControl size={size} sx={{ width: { xs: '100%', sm: 280, md: 320 } }}>
      <InputLabel>Directory</InputLabel>
      <Select
        value={selectedDirectory?.id || ''}
        label="Directory"
        variant="filled"
        onChange={handleChange}
        sx={{
          '& .MuiSelect-select': {
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
          }
        }}
      >
        {directories.length === 0 ? (
          <MenuItem disabled>No directories available</MenuItem>
        ) : (
          directories.map((directory) => (
            <MenuItem key={directory.id} value={directory.id}>
              {directory.name} {directory.id.startsWith('cmd-dir-') ? '(from command)' : ''}
            </MenuItem>
          ))
        )}
      </Select>
    </FormControl>
  );
};

export const DirectorySelector = React.memo(DirectorySelectorComponent);

// src/CommandRunner.Website.VueJs/src/components/DirectorySelector.vue
<script setup lang="ts">
import type { FavoriteDirectoryDto } from '../services/api';

const props = defineProps<{
  directories: FavoriteDirectoryDto[];
  selectedDirectory: FavoriteDirectoryDto | null;
}>();

const emit = defineEmits<{
  change: [directory: FavoriteDirectoryDto | null];
}>();

function handleChange(event: Event) {
  const id = (event.target as HTMLSelectElement).value;
  emit('change', props.directories.find((d) => d.id === id) ?? null);
}
</script>

<template>
  <div class="field directory-selector">
    <label class="field__label" for="directory-selector">Directory</label>
    <select
      id="directory-selector"
      class="field__control"
      :value="selectedDirectory?.id ?? ''"
      @change="handleChange"
    >
      <option v-if="directories.length === 0" value="" disabled>No directories available</option>
      <option v-for="directory in directories" :key="directory.id" :value="directory.id">
        {{ directory.name }}{{ directory.id.startsWith('cmd-dir-') ? ' (from command)' : '' }}
      </option>
    </select>
  </div>
</template>

<style scoped>
.directory-selector {
  width: 100%;
  max-width: 320px;
}
</style>
