// src/CommandRunner.ReactWebsite/src/components/ProfileSelector.tsx
import React from 'react';
import { FormControl, InputLabel, Select, MenuItem, SelectChangeEvent } from '@mui/material';
import { ProfileDto } from '../services/api';

interface ProfileSelectorProps {
  profiles: ProfileDto[];
  selectedProfile: ProfileDto | null;
  onProfileChange: (profile: ProfileDto | null) => void;
  size?: 'small' | 'medium';
}

const ProfileSelectorComponent: React.FC<ProfileSelectorProps> = ({
  profiles,
  selectedProfile,
  onProfileChange,
  size = 'medium'
}) => {
  const handleChange = (event: SelectChangeEvent<string>) => {
    const profileId = event.target.value;
    const profile = profiles.find(p => p.id === profileId) || null;
    onProfileChange(profile);
  };

  return (
    <FormControl size={size} sx={{ width: { xs: '100%', sm: 280, md: 320 } }}>
      <InputLabel>Profile</InputLabel>
      <Select
        value={selectedProfile?.id || ''}
        label="Profile"
        variant="filled"
        onChange={handleChange}
        sx={{
          '& .MuiSelect-select': {
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
          }
        }}
      >
        {profiles.length === 0 ? (
          <MenuItem disabled>No profiles available</MenuItem>
        ) : (
          profiles.map((profile) => (
            <MenuItem key={profile.id} value={profile.id}>
              {profile.name}
            </MenuItem>
          ))
        )}
      </Select>
    </FormControl>
  );
};

export const ProfileSelector = React.memo(ProfileSelectorComponent);

// src/CommandRunner.Website.VueJs/src/components/ProfileSelector.vue
<script setup lang="ts">
import type { ProfileDto } from '../services/api';

const props = defineProps<{
  profiles: ProfileDto[];
  selectedProfile: ProfileDto | null;
  compact?: boolean;
}>();

const emit = defineEmits<{
  change: [profile: ProfileDto | null];
}>();

function handleChange(event: Event) {
  const id = (event.target as HTMLSelectElement).value;
  emit('change', props.profiles.find((p) => p.id === id) ?? null);
}
</script>

<template>
  <div class="field profile-selector" :class="{ 'profile-selector--compact': compact }">
    <label class="field__label" for="profile-selector">Profile</label>
    <select
      id="profile-selector"
      class="field__control"
      :value="selectedProfile?.id ?? ''"
      @change="handleChange"
    >
      <option v-if="profiles.length === 0" value="" disabled>No profiles available</option>
      <option v-for="profile in profiles" :key="profile.id" :value="profile.id">
        {{ profile.name }}
      </option>
    </select>
  </div>
</template>

<style scoped>
.profile-selector {
  width: 100%;
  max-width: 320px;
}
</style>
